# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  OS_LOCAL_KEYPAIR_NAME = "#{ENV['USER']}-osdev"
  OS_LOCAL_KEYPAIR = "/home/#{ENV['USER']}/.ssh/#{ENV['USER']}-osdev"

  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = OS_LOCAL_KEYPAIR

  config.vm.provider "openstack" do |os|
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.tenant_name        = ENV['OS_TENANT_NAME']
    os.region             = ENV['OS_REGION_NAME']
    os.sync_method        = 'none'

    os.keypair_name       = OS_LOCAL_KEYPAIR_NAME
    os.public_key_path    = OS_LOCAL_KEYPAIR + '.pub'
    os.networks           = ['network1']
    os.server_name        = "lingxian_ubuntu_packaging"
    os.flavor             = 'c1.c1r4'
    os.security_groups    = ['default']
    os.image              = 'ubuntu-14.04-x86_64'
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y packaging-dev
  SHELL
end
